### ISSUE TITLE
Image deletion is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#10967]
### What
- Image deletion is broken (seems JS related)
- https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=8594019170028
![Image](https://github.com/user-attachments/assets/8466eff0-e369-4fb7-ac37-a00cf09c81ef)

Uncaught TypeError: Cannot read properties of null (reading 'length')
    at Object.success (userscript.html?name=Folksonomy-Engine-user-script.user.js&id=37d8ec89-042f-4422-a024-597fe802bda1:691:30)
    at l (userscript.html?name=Folksonomy-Engine-user-script.user.js&id=37d8ec89-042f-4422-a024-597fe802bda1:26:22398)
    at Object.fireWith [as resolveWith] (userscript.html?name=Folksonomy-Engine-user-script.user.js&id=37d8ec89-042f-4422-a024-597fe802bda1:26:23209)
    at n (userscript.html?name=Folksonomy-Engine-user-script.user.js&id=37d8ec89-042f-4422-a024-597fe802bda1:26:62220)
    at XMLHttpRequest.<anonymous> (userscript.html?name=Folksonomy-Engine-user-script.user.js&id=37d8ec89-042f-4422-a024-597fe802bda1:26:67990)Understand this errorAI
/state/brands-to-be-completed/code/859401917xxxx&json=1:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()Understand this errorAI
product.pl?type=edit&code=8594019170028:4321 Uncaught TypeError: $(...).foundation is not a function
    at Object.callback (product.pl?type=edit&code=8594019170028:4321:16)
    at HTMLAnchorElement.<anonymous> (foundation.js:1223:18)
    at HTMLDocument.dispatch (jquery.js:25:1315)
    at v.handle (jquery.js:24:30111)Understand this errorAI
product-multilingual.js:1267 Uncaught TypeError: $(...).ajaxSubmit is not a function
    at HTMLAnchorElement.<anonymous> (product-multilingual.js:1267:28)
    at HTMLAnchorElement.dispatch (jquery.js:25:1315)
    at v.handle (jquery.js:24:30111)

**Comment by alexgarel** [comment]
I tried it again (but one image at a time) and it worked !
Maybe it is because you were removing both ?

**Comment by stephanegigandet** [comment]
no further reports, closing
