### ISSUE TITLE
Github tests fail because too many things are printed to STDERR

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3125]
```
   'nutriment canonicalized {label => "Omega 3-vetzuren",lc => "nl",nid => "omega-3-fat"}\n' +
    'initializing sublabel {lc => "nl",nid => "omega-3-fat",sublabel => "omega-3-fat"}\n' +
    'nutriment canonicalized {label => "Om'
}
(node:35902) UnhandledPromiseRejectionWarning: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
    at Socket.onChildStderr (child_process.js:386:14)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:271:13)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
(node:35902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35902) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by teolemon** [comment]
believe it was fixed by @hangy. Closing
