### ISSUE TITLE
Wiki crash

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#807]
```[f786de351e533db2d30de927] /OpenPetFoodFacts MWException from line 132 of /var/www/off.wiki.en/includes/cache/localisation/LCStoreCDB.php: Error writing to CDB file "/tmp/l10n_cache-en.cdb.tmp.194406426".

Backtrace:

#0 /var/www/off.wiki.en/includes/cache/localisation/LocalisationCache.php(1027): LCStoreCDB->set(string, boolean)
#1 /var/www/off.wiki.en/includes/cache/localisation/LocalisationCache.php(464): LocalisationCache->recache(string)
#2 /var/www/off.wiki.en/includes/cache/localisation/LocalisationCache.php(381): LocalisationCache->initLanguage(string)
#3 /var/www/off.wiki.en/includes/cache/localisation/LocalisationCache.php(296): LocalisationCache->loadSubitem(string, string, string)
#4 /var/www/off.wiki.en/languages/Language.php(2583): LocalisationCache->getSubitem(string, string, string)
#5 /var/www/off.wiki.en/includes/cache/MessageCache.php(870): Language->getMessage(string)
#6 /var/www/off.wiki.en/includes/cache/MessageCache.php(826): MessageCache->getMessageForLang(Language, string, boolean, array)
#7 /var/www/off.wiki.en/includes/cache/MessageCache.php(766): MessageCache->getMessageFromFallbackChain(Language, string, boolean)
#8 /var/www/off.wiki.en/includes/Message.php(1188): MessageCache->get(string, boolean, Language)
#9 /var/www/off.wiki.en/includes/Message.php(802): Message->fetchMessage()
#10 /var/www/off.wiki.en/includes/Message.php(902): Message->toString()
#11 /var/www/off.wiki.en/includes/user/User.php(869): Message->text()
#12 /var/www/off.wiki.en/includes/user/User.php(1081): User::isUsableName(string)
#13 /var/www/off.wiki.en/includes/user/User.php(529): User::getCanonicalName(string, string)
#14 /var/www/off.wiki.en/extensions/mediawiki-extensions-sessionprovider-productopener-master/AuthProductOpener.body.php(105): User::newFromName(string, string)
#15 /var/www/off.wiki.en/extensions/mediawiki-extensions-sessionprovider-productopener-master/AuthProductOpener.body.php(65): AuthProductOpener->newSessionForRequest(array, WebRequest)
#16 /var/www/off.wiki.en/includes/session/SessionManager.php(486): AuthProductOpener->provideSessionInfo(WebRequest)
#17 /var/www/off.wiki.en/includes/session/SessionManager.php(189): MediaWiki\Session\SessionManager->getSessionInfoForRequest(WebRequest)
#18 /var/www/off.wiki.en/includes/WebRequest.php(735): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#19 /var/www/off.wiki.en/includes/session/SessionManager.php(128): WebRequest->getSession()
#20 /var/www/off.wiki.en/includes/Setup.php(759): MediaWiki\Session\SessionManager::getGlobalSession()
#21 /var/www/off.wiki.en/includes/WebStart.php(137): require_once(string)
#22 /var/www/off.wiki.en/index.php(40): require(string)
#23 {main}```

**Comment by VaiTon** [comment]
Is it still an issue? @teolemon

**Comment by VaiTon** [comment]
Closing for inactivity.
