### ISSUE TITLE
Error: Invalid LatLng object: (NaN, NaN)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#855]
Error: Invalid LatLng object: (NaN, NaN) - 3 times - click to see details
Steps to reproduce
Open https://world.openfoodfacts.org/packager-code/fr-42-156-006-ec
Mouseup < div id="container" class="leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom" >
Traceback
```Error: Invalid LatLng object: (NaN, NaN)
    at o.LatLng (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:14144)
    at Object.unproject (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:18043)
    at Object.pointToLatLng (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:18432)
    at e.unproject (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:30416)
    at e.layerPointToLatLng (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:30532)
    at e._fireDOMEvent (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:6:3810)
    at e._handleDOMEvent (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:6:3247)
    at HTMLDivElement.h (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:6:11430)
    at setTimeout (<anonymous>:686:32)
```
Steps to reproduce
Open https://world.openfoodfacts.org/packager-code/fr-42-156-006-ec
Mousemove < div id="container" class="leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom" >
Traceback
```Error: Invalid LatLng object: (NaN, NaN)
    at o.LatLng (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:14144)
    at Object.unproject (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:18043)
    at Object.pointToLatLng (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:18432)
    at e.unproject (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:30416)
    at e.layerPointToLatLng (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:30532)
    at e._fireDOMEvent (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:6:3810)
    at e._handleDOMEvent (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:6:3247)
    at HTMLDivElement.h (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:6:11430)
    at setTimeout (<anonymous>:686:32)
```
Steps to reproduce
Open https://world.openfoodfacts.org/packager-code/fr-42-156-006-ec
Contextmenu < div id="container" class="leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom" >
Traceback
```Error: Invalid LatLng object: (NaN, NaN)
    at o.LatLng (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:14144)
    at Object.unproject (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:18043)
    at Object.pointToLatLng (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:18432)
    at e.unproject (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:30416)
    at e.layerPointToLatLng (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:5:30532)
    at e._fireDOMEvent (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:6:3810)
    at e._handleDOMEvent (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:6:3247)
    at HTMLDivElement.h (https://static.openfoodfacts.org/bower_components/leaflet/dist/leaflet.js:6:11430)
    at setTimeout (<anonymous>:686:32)```

**Comment by hangy** [comment]
Are you still getting that issue @teolemon? https://world.openfoodfacts.org/packager-code/fr-42-156-006-ec does not show any JS errors for me, right now.

**Comment by teolemon** [comment]
LGTM. You may close.
